<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>01f83e6c-6262-4b83-b178-966cdb5e5899</testSuiteGuid>
   <testCaseLink>
      <guid>0affc44d-d1f1-42b5-aee4-f15455c87fa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test4</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c01b9dca-62a8-4646-a2c8-b0c5e247cb6b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c01b9dca-62a8-4646-a2c8-b0c5e247cb6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>25e133f4-b421-43f0-8abf-e90e417110a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c01b9dca-62a8-4646-a2c8-b0c5e247cb6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>e3c70a78-938e-4e7d-b2ff-72513d67693e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
